-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T 
    ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
        SELECT A.ITEM_ID
        FROM ITEM_INFO A JOIN ITEM_TREE B
        ON A.ITEM_ID = B.ITEM_ID
        WHERE RARITY = 'RARE')
ORDER BY I.ITEM_ID DESC;